### ISSUE TITLE
[FEATURE] Change name in command palette in case of different exercises with same name

### ISSUE THREAD

**Issue by BTWS2** [thepieterdc/dodona-plugin-vscode#102]
**Briefly describe the feature idea:**
I would like to suggest a new way to handle the case of different exercises with same name.
![image](https://user-images.githubusercontent.com/56451049/114555005-962c9200-9c67-11eb-9c5a-c61663dce9cd.png)

It's confusing/unexpected for the user that there is a new window. Since a certain workplace is opened, we assume the file should be in the same folder, only the name should change. I would propose that the user could enter/modify the name in the command palette, just like the [File Utils Visual Studio Code extension `File Utils: Rename` command](https://marketplace.visualstudio.com/items?itemName=sleistner.vscode-fileutils) (fileutils.renameFile). The name (and not the extension) should be selected and the user should enter the new filename and press enter (see image).

![image](https://user-images.githubusercontent.com/56451049/114552186-9a0ae500-9c64-11eb-9ff2-14fc9bb1bfa9.png)

**Comment by stijndcl** [comment]
I believe we did it like this at first, but we felt like it didn't stand out as much. We wanted to make sure that the user would notice that something was wrong & that they had to enter a new filename. A big pop-up window felt like a better solution.

**Comment by BTWS2** [comment]
It's true that a new window is more noticeable, the only downside is that the user doesn't know why there is a new window and what they have to do. The command palette is more hidden but allows to explain what happened. I asked the some colleagues what they prefer and will get back to you.

**Comment by stijndcl** [comment]
Hmm, that's true. A message with some info would definitely be appropriate, I didn't think of that.

**Comment by BTWS2** [comment]
My colleague prefers the file explorer, but maybe there is a possibility to add a message somehow. This issue isn't urgent as this case doesn't happen very often.
