### ISSUE TITLE
[FEATURE] Add comment syntax for new languages on Dodona

### ISSUE THREAD

**Issue by BTWS2** [thepieterdc/dodona-plugin-vscode#249]
Is this the only needed change in https://github.com/thepieterdc/dodona-plugin-vscode/blob/master/src/util/comments.ts?

```typescript
const exclamation = (text: string) => `<!-- ${text} -->`;

html: exclamation,
sql: dashes,
```

If so, I'm willing to make a PR for it.

**Comment by stijndcl** [comment]
That should be enough to make it work.
