### ISSUE TITLE
[BUG] Images in exercise descriptions are not displayed

### ISSUE THREAD

**Issue by BTWS2** [thepieterdc/dodona-plugin-vscode#32]
# Description
Images in exercise descriptions are not displayed.

# Environment
- OS: Windows 10
- Plugin version: 1.0.0
- Screenshot of the `Help -> About` screen
![image](https://user-images.githubusercontent.com/56451049/94372587-4c32f300-00ff-11eb-83e5-5730607f5afc.png)

# Screenshots
![image](https://user-images.githubusercontent.com/56451049/94372734-8781f180-0100-11eb-8767-25a1760aefd0.png)

**Comment by stijndcl** [comment]
We are aware of this, this is caused by Content Security Policy.

**Comment by thepieterdc** [comment]
https://github.com/dodona-edu/dodona/pull/2298
