### ISSUE TITLE
[FEATURE] Check in subdirectories when creating new exercise

### ISSUE THREAD

**Issue by BTWS2** [thepieterdc/dodona-plugin-vscode#334]
Students have a workspace which is a folder with a subfolder for each chapter. Currently the extension doesn't look in subfolders to check if the exercise already exists. Students now have to open each chapter as a separate workspace. It would be easier if all chapters are in one workspace if students want to look at exercises from the previous chapter(s).

This feature is brought up by M. Denert.

https://github.com/thepieterdc/dodona-plugin-vscode/blob/e70d5809b882c6d8b4807a1b1448adf9680ac429/src/commands/createNewExercise.ts#L29

**Comment by thepieterdc** [comment]
Not really sure how we would go on to implement this. Things to keep in mind:

- You can have a large amount of exercises and calling readFileSync on all of them will be very slow.
- The subfolder can have an arbitrary name (examples: hoofdstuk1/, hoofdstuk-1/, chapter_1/, chapter1-ifstatements/, ...) which would end up in the previous bullet point as well.
- What do we do in case of a custom filename.
- What do we do in the case of duplicated exercise names (eg the ISBN exercise that exists in multiple chapters)

**Comment by stijndcl** [comment]
Indeed, the only real "solution" to these is checking every single file in every single subdirectory to see if one of them has the same Dodona url in a comment somewhere, which is just not feasible. It would be immensely slow & make the plugin really annoying to use (especially for big courses).

**Comment by BTWS2** [comment]
I agree with your remarks, I'm closing this issue.
