### ISSUE TITLE
[FEATURE] Set User-Agent when contacting Dodona

### ISSUE THREAD

**Issue by chvp** [thepieterdc/dodona-plugin-vscode#420]
Currently, when contacting Dodona, the default `got` User-Agent (`got (https://github.com/sindresorhus/got)`). This makes it hard to see whether unusual traffic is coming from the VSCode extension or from someone else scripting.

**Comment by bmesuere** [comment]
This should be easy to set by adding a `user-agent` header [here](https://github.com/thepieterdc/dodona-plugin-vscode/blob/master/src/api/client.ts#L44) and a few lines below. If possible, it would also be nice to include the extension version.
