### ISSUE TITLE
[FEATURE] Default `Dodona: submit solution` shortcut

### ISSUE THREAD

**Issue by BTWS2** [thepieterdc/dodona-plugin-vscode#51]
Suggestions:
* Easy to press with small left hand, right hand can stay on the mouse.
* Only two keys to press. Three keys defeat the purpose of a shortcut.
* Keys are not far apart on AZERTY keyboard.
* Key combination isn't in use.

If a good shortcut is chosen, it removes a step from the installation guide. If users want another combination, they can change it.

**Comment by stijndcl** [comment]
The homepage shows instructions for users to create a custom keybind, this does not necessarily have to be three keys, so they can create a two-key shortcut if they really want one. Do you have any suggestions for shortcuts? Many of the obvious two-button combinations are already in use.

**Comment by BTWS2** [comment]
Indeed, `shift` and `ctrl` are not an option because most of the combinations are taken. Some suggestions (in this order):
1. ~~`Alt + s`  (from **S**ubmit **s**olution)~~ (already in use for `Selection` in toolbar at the top)
2. `Alt + d` (from **D**odona) ✅
3. `Alt + a` (from Dodon**a**)
3. `Alt + e` (from **E**valuate)
