### ISSUE TITLE
[FEATURE] Optional Dodona Light & Dark themes

### ISSUE THREAD

**Issue by stijndcl** [thepieterdc/dodona-plugin-vscode#56]
**Briefly describe the feature idea:**
Add the Dodona light & dark themes as an optional theme to use when installing the plugin. These could optionally be toggles in the configurations, but they should mainly be added as themes the user can select. This idea was proposed in #55, but I don't like the idea of forcing the user's IDE to use a specific theme, and rather have it be an option that they can toggle if they wish to use it. Dodona Font could potentially be used as well.

**Comment by BTWS2** [comment]
I didn't express myself well. I don't want to change the theme of VS Code, only the mode (light/dark) of the content on a activity description or reading activity. I clarified the issue in #55.
![image](https://user-images.githubusercontent.com/56451049/94565963-1d855b80-026a-11eb-9d93-0d00c8fe01c0.png)
