### ISSUE TITLE
[FEATURE] Add button to show series(/course?) description as activity description

### ISSUE THREAD

**Issue by BTWS2** [thepieterdc/dodona-plugin-vscode#59]
If students make a test, sometimes important information is in the series description.

![image](https://user-images.githubusercontent.com/56451049/94731382-f52e5780-0364-11eb-9720-800f9a0b0f85.png)

Is it possible to add a document icon to series? Clicking it shows the series description like an activity description. Maybe also a document icon next to the course for the course description?

**Comment by stijndcl** [comment]
This is currently not supported in the Dodona API, but I've added it myself & created a [pull request](https://github.com/dodona-edu/dodona/pull/2314) for it. Will do this later once it's merged.

**Comment by stijndcl** [comment]
@BTWS2 This suggestion was _[denied](https://github.com/dodona-edu/dodona/pull/2314)_, and as a result this will not be implemented.

**Comment by BTWS2** [comment]
I somewhat agree with Bart. My main focus was the **series description**. Making a full blown Dodona client was not my intention.

I use series descriptions for some important remarks just before students start with the test, some examples:
* Don't forget type hinting
* Add comments where necessary
* Even if Dodona doesn't marks it as correct, you can still earn points
* Small introduction for the exercises if they are about the same subject. Sometimes one big exercise consists of multiple exercises. First some separate functions and integrating them in the last exercise for example.
* Tell which exercises are mandatory, optional and which exercises are for preparing for the test (not a test use case)
* ...

If students use the VS Code extension they almost never see the series description. **This way they may be missing out on important information.** They see the results when they click the results table if they click the `view the results`.

Maybe an **alternative solution is linking to the series description** (and course?) **on dodona.ugent.be** with the `edit.svg` icon, instead of displaying it in VS Code itself? This is in alignment with the vision of Bart and sends users to the Dodona website. The icon would appear when the mouse hover over the name.

This would example below would link to https://dodona.ugent.be/nl/courses/293/ and https://dodona.ugent.be/nl/courses/293/#series-2561-0-proloog.

![image](https://user-images.githubusercontent.com/56451049/95125115-c2b19f80-0754-11eb-96e7-365668b2428e.png)

**Comment by stijndcl** [comment]
I can see how that is a better solution than integrating it into the plugin itself, but that would still mean students would have to click on that button to check the link & see if there is any important info on that page. As a student myself I think I can confidently say that you can't guarantee people will do that, even if the button is there.

I think some sort of in-your-face popup might be required that checks whether or not the series actually *has* a description attached to it, and notifying the user when it does. That might be a viable solution (combining it with your proposal, so students can always click on it themselves). When a student opens a new exercise in a series with a description, and they have never made an exercise in that series before (to avoid spamming it), they should be notified that the description might contain important information?

**Comment by BTWS2** [comment]
I like how this is evolving. I think we can agree that having the button in the Tree View is better than nothing. This improves the navigation to the course and series description, points to possibly important information and saves a few clicks. If students use the extension during the semester they will already be accustomed to what the button does (I hope).

The in-your-face pop-up might be a bit much, but a reminder doesn't hurt like you pointed out. I think a notification in the right hand corner with a button (similar to when they submitted a solution) that links to the series description on dodona.ugent.be should be ok. If students use the extension during the semester they will already be accustomed to what the notification means (I hope). Is it possible to check if a series has a description with the current API? This is a nice feature, but I already would be happy with what we discussed. Showing a notification when they open a new exercise in a series where they have never made an exercise in that series before, is a good idea!

**Comment by stijndcl** [comment]
> Is it possible to check if a series has a description with the current API? This is a nice feature, but I already would be happy with what we discussed.

Yes, it is. This would indeed make it possible to implement both of our idea's. Re-opened this issue & will try to get it done in the coming days (unless someone from the Dodona team votes against that as well, but I don't see why they would as it only holds positive outcomes).
