### ISSUE TITLE
[FEATURE] Notify user if there is a new code remark and link to Dodona

### ISSUE THREAD

**Issue by BTWS2** [thepieterdc/dodona-plugin-vscode#62]
Bart brought up an interesting point. If there is new feedback available, students don't see the bell icon immediately if they use the extension.

I already had several occasions where I gave feedback on code and students only noticed it 15 minutes (or more) later when programming. Is this feature request possible with the current API?

![image](https://user-images.githubusercontent.com/56451049/95186535-625d4500-07ca-11eb-9136-08e9fe095427.png)

I think there are two ways (or both) to solve this problem (and should be in alignment with the vision of Bart because it sends users to the Dodona website):
* Notification in right-hand corner when there is a new remark on code with a button that links to https://dodona.ugent.be/nl/notifications/.
* Bell icon in the top of the Tree View, that shows the same behavior as on Dodona (without showing the list of notifications). The bell should only show **if** there is a new unread remark. Clicking the bell icon should link to https://dodona.ugent.be/nl/notifications/.

![image](https://user-images.githubusercontent.com/56451049/95186692-8a4ca880-07ca-11eb-8906-2ee03535ac19.png) ![image](https://user-images.githubusercontent.com/56451049/95186713-933d7a00-07ca-11eb-9c71-add1db2d7cd9.png)

**Comment by stijndcl** [comment]
This does sound like a really good idea, I hadn't thought of the Dodona notifications yet. I just looked around a bit and it looks like it should be doable. This could run as a background task that checks Dodona every few minutes (doing it constantly would be really bad performance-wise), considering notifications on Dodona are not very common.

**Comment by stijndcl** [comment]
I've implemented everything except the dynamically changing bell icon. Not quite sure on how I'm gonna do that yet, but the information message bottom-right is already a thing at least (and the bell can be clicked to open notifications).

After looking around I didn't find any useful information on how to make the ViewAction's `when` clause change dynamically from code, or after triggering something.

**Comment by BTWS2** [comment]
Thank you! Is a 30 second interval doable for Dodona? If 500 to 1000 students use VS Code simultaneously will it still work without issues? The time of the interval is the worst-case scenario, so an interval of 1 or 2 minutes is also ok for me. Notifications don't happen that often.

I did some research and this is what I found, but I don't know if it's helpful:
* I noticed the SQL Server extension uses a changing icon to Start/Pause Query History Capture ([Source code](https://github.com/microsoft/vscode-mssql/search?q=start+query+history+capture)).
![image](https://user-images.githubusercontent.com/56451049/95257227-4c7c6e00-0824-11eb-9e7b-854e8cc80949.png)
* https://stackoverflow.com/questions/55527587/vs-code-updating-icons-in-treeview-in-custom-viewscontainer but is only a question, not an answer.

**Comment by stijndcl** [comment]
I'm not sure, I'll ask someone from Dodona what type of interval they'd be most comfortable with. I went with 30 seconds because my initial idea was a few minutes to increase performance, but I found out it only takes a few ms to do it & it was really inexpensive.

Also thank you for the link, I'm sure there's something in there that could be of use.

**Comment by BTWS2** [comment]
Adding this for reference and might be useful: https://github.com/dodona-edu/dodona/pull/2302

**Comment by stijndcl** [comment]
Where would you put this? I don't immediately see a place where this would fit in.

**Comment by BTWS2** [comment]
It was mainly for the fact that Dodona only checks the status of the notifications once every minute. They also show how many, but for the extension showing if there are notifications should be enough.

**Comment by stijndcl** [comment]
Ah, I thought you referenced the PR itself instead of the one mentioned lower. In that case I'll go for every minute.
