### ISSUE TITLE
[BUG] Single-line exercises not possible due to exercise link

### ISSUE THREAD

**Issue by Prozilla** [thepieterdc/dodona-plugin-vscode#720]
# Description
Single-line shell script exercises can't be submitted via the vscode plugin using the vscode editor, because it requires a comment with a link to the exercise on the first line. This first line is evaluated as part of the shell script in Dodona, making the command invalid and making the exercise always fail.

## Expected Behavior

- Open exercise:

```sh
/* https://dodona.be/nl/courses/4165/series/46398/activities/578459704 */

```

- Complete exercise in editor like this:

```sh
/* https://dodona.be/nl/courses/4165/series/46398/activities/578459704 */

echo "Hello world!"
```

- Submit solution
- Get notification 'Solution to "Example" has been accepted!'

## Actual Behavior

- Complete exercise in editor like this:

```sh
/* https://dodona.be/nl/courses/4165/series/46398/activities/578459704 */

echo "Hello world!"
```

- Submit solution
- Get notification 'Solution to "Example" was not correct: verkeerd antwoord'
- Dodona seems to evaluate the first line as a shell command (which fails and is unexpected because it is expected to be treated as a comment)
- Output of failed tests on Dodona is '/bin/bash: line 1: /bin: Is a directory"

### Alternative

- Remove the automatically added first line from the shell script
- Complete exercise in editor like this:

```sh
echo "Hello world!"
```

- Submit solution
- Get notification 'No exercise link found. Make sure the first line of the file contains a comment with the link to the exercise.'

## Steps to Reproduce

  1. Start any shell exercise that expects the solution on a single line
  1. Try to submit with/without the comment with the link to the exercise in the editor
  
# Proposed solutions

- Detect file format when exercise is opened and adjust comment on first line accordingly (use `# url` instead of `/* url */`)
- Automatically remove first line before sending solution to Dodona

# Environment
- OS: Windows 11
- Plugin version: v2.0.0
![image](https://github.com/user-attachments/assets/47f9a1e3-a932-4cf5-8cf3-127a340ad7e1)

**Comment by BTWS2** [comment]
This is similar to https://github.com/thepieterdc/dodona-plugin-vscode/pull/252.

Does this code work on Dodona? If so, can you make a PR (src/util/comments.ts)?

```bash
# https://dodona.be/nl/courses/4165/series/46398/activities/578459704

echo "Hello world!"
```

**Comment by Prozilla** [comment]
That snippet works, I will try to make a PR

**Comment by Beaness** [comment]
Is the bash programming language defined as "bash" or "sh"?  (this is needed for the comment mapping)

**Comment by BTWS2** [comment]
If I remember correctly, you can base yourself on this: https://dodona.be/nl/programming_languages/

![image](https://github.com/user-attachments/assets/fa97c017-713d-4244-9e6c-a635706a4c98)

This is the information about the mentioned exercise:
![image](https://github.com/user-attachments/assets/a5c72814-f615-47c4-9144-750c8c542a66)
