### ISSUE TITLE
[FEATURE] Toggle to only show favorite courses

### ISSUE THREAD

**Issue by BTWS2** [thepieterdc/dodona-plugin-vscode#74]
This is a feature request from Marleen Denert who has a lot of courses in the sidebar and would like a way to show only the relevant ones in a logical order. Some courses have the same name but are from a different academic year.

* Setting (toggle) to only show favorite courses (off by default). This would resemble the sidebar on dodona.ugent.be (but alphabetically):
![image](https://user-images.githubusercontent.com/56451049/102476792-cbc7c280-405b-11eb-83b1-87aaafcf5d97.png)
* Setting (toggle) to sort by academic year (descending order) in the first place and sort alphabetically second.

**Comment by stijndcl** [comment]
The Dodona API does not supply a field stating whether or not a course has been favourited, so the first option is not possible. The second one should be no more than a simple sort though (:tm:), that sounds doable.

**Comment by BTWS2** [comment]
Sorting sounds good to me. 

Maybe the teacher can enter which academic years should be visible in the settings, with commas in between? For example

> 2020, 2019

or

> 2020–2021, 2019–2020

And/or a setting to specify which courses should be shown with the number from the link e.g. https://dodona.ugent.be/nl/courses/293/ (imitating the favorite feature)? Courses from the teacher with preparations for a test or exam can be hidden this way when the teacher gives a demo.

> 136, 293

**Comment by stijndcl** [comment]
I can see how it would be useful for teachers to gain the ability to hide courses from students. It might be beneficial to make this available to students as well, however, so that unwanted courses can indeed be filtered out.

I'm currently working on a project that's due sunday though, so it might take a few days to make this.

**Comment by BTWS2** [comment]
Yes indeed, I had the use case of teachers in mind, but students can also benefit from that feature. No problem, thank you.
