### ISSUE TITLE
[Feature] Make a difference between courses with similar names

### ISSUE THREAD

**Issue by mcbloch** [thepieterdc/dodona-plugin-vscode#88]
**Make a difference between courses with similar names.**

Courses are sometimes difficult to tell appart. It's possible to follow a course for multiple years or that courses share a name.

You can get something list this in the `activities` list.
![image](https://user-images.githubusercontent.com/12089026/108718583-e4060300-751e-11eb-953e-9494adaaea52.png)

In Dodona you can see the difference because of the year of the course and professor giving it. 
![image](https://user-images.githubusercontent.com/12089026/108718712-04ce5880-751f-11eb-8809-c00421f2bf31.png)
![image](https://user-images.githubusercontent.com/12089026/108719181-8a520880-751f-11eb-8c49-d373a5efca64.png)

**Comment by stijndcl** [comment]
Oh wow I hadn't considered this was a possibility, thanks for pointing it out! I'll look into it later today.

Until I've come up with a fix, you can see which one it is based on your [``sorting options``](https://github.com/thepieterdc/dodona-plugin-vscode#sorting-and-filtering-courses-usage), the ``academic year`` parameter will help guide you which course is which. If ``academic year`` is set to ``descending``, the most recent course (2020-2021) will be higher up & vice-versa.
