### ISSUE TITLE
[BUG] Exercise incorrectly marked as solved or wrong

### ISSUE THREAD

**Issue by mcbloch** [thepieterdc/dodona-plugin-vscode#94]
# Description
I have a course I had last year also.
Results from that course from last year incorrectly carry over to my course of this year.
So in the dodona UI, in the 2019-2020 version of the course, exercise A is solved.
In the 2020-2021 version it is not yet solved.
The plugin shows both years as solved. It also does this for an exercise C which I had wrong. The plugin also shows it as wrong in the 2020-2021 year altough I didn't yet do it.

# Environment
- OS: [Void Linux 5.10.16_1]
- Plugin version: (e.g. v1.5.0)
- 
![image](https://user-images.githubusercontent.com/12089026/110107402-1d563280-7dab-11eb-89db-b5ca43d9fbd2.png)

**Comment by stijndcl** [comment]
If I remember correctly, we actually get your exercise's status right from Dodona. I _think_ that if it's the same exercise over multiple courses, some of the submission data might be linked together, so Dodona tells us you actually have solved it already. I'm gonna ask you to try a few things here to diagnose this (I don't have any Dodona courses that I'm taking from previous years, so I can't really debug this myself).

- Take the URL of the exercise in both the old course (2019 - 2020) and the new course (2020 - 2021). The URLs end with `/activities/XXXXXXX`, which is the unique ID of the exercise. Are the ID's in both exercises the same?

- Can you go to the exercise in the **new** course (2020 - 2021), scroll down to the bottom, and check your submissions there? Are your old submissions visible in the new course?

![image](https://user-images.githubusercontent.com/60451863/110120119-e8eb7200-7dbc-11eb-9188-d2fde32fd88b.png)

- Also, if you go to the URL of the exercise and add ".json" at the end, (for example, `https://dodona.ugent.be/nl/courses/123/series/456/activities/789.json`), what does it say under `last_solution_is_best`, `has_solution`, and `has_correct_solution`?

**Comment by mcbloch** [comment]
1) The activity id's of both the exercises are the same.
2) The submissions are not visible in the new course. This year has no tries and last year has 4.
3) The json for both execises say
```json
"last_solution_is_best":true,"has_solution":true,"has_correct_solution":true
```

My guess is that the api sees the activity as unique as where I'd expect the combination of course+series+activities to be unique -> `https://dodona.ugent.be/nl/courses/xxx/series/yyyy/activities/zzzzzzzzzz/#`

**Comment by stijndcl** [comment]
That's also what I would have expected. One more thing - if you go to the URL of your exercise in the **new** course and add ``/submissions`` at the end, does it show anything over there? The only fix I can think of is checking if there are submissions for this exercise or not, otherwise I'm afraid there's not a lot we can do about this, it's more related to the Dodona API. ``https://dodona.ugent.be/nl/courses/xxx/series/yyyy/activities/zzzzzzzzzz/submissions``

**Comment by BTWS2** [comment]
@stijndcl I just checked with the [PyCharm plugin](https://github.com/thepieterdc/dodona-plugin-jetbrains) and it shows the same behavior. Different courses pointing at the same exercise show the same status.

**Comment by mcbloch** [comment]
> That's also what I would have expected. One more thing - if you go to the URL of your exercise in the **new** course and add `/submissions` at the end, does it show anything over there? `https://dodona.ugent.be/nl/courses/xxx/series/yyyy/activities/zzzzzzzzzz/submissions`.

No it doesn't show anything.

**Comment by mcbloch** [comment]
I think the change should be in the dodona api. It should take into account the course the activity is in no?

**Comment by mcbloch** [comment]
Do I create an issue for this on the Dodona platform?

**Comment by chvp** [comment]
This should be fixed in the Dodona API. An issue there is definitely appropriate.

**Comment by stijndcl** [comment]
In that case I'm closing this issue here.
