### ISSUE TITLE
[BUG] Open exercise description when file already exists

### ISSUE THREAD

**Issue by BTWS2** [thepieterdc/dodona-plugin-vscode#97]
# Steps to reproduce
1. Make an exercise with the treeview
2. Close programming file and exercise description
3. Open the exercise that already exists with the treeview
4. The exercise description doesn't open

# Steps to reproduce
1. Click on an exercise to open with the treeview
2. Click on another exercise
3. Reopen the first exercise
4. The exercise description doesn't open

**Comment by stijndcl** [comment]
I think this was accidentally refactored out yesterday @thepieterdc

**Comment by BTWS2** [comment]
Are you able to reproduce these steps? When I try these steps, the description doesn't open (correctly).

Case 1:
https://user-images.githubusercontent.com/56451049/110780776-59830a80-8265-11eb-80b3-c3d016706565.mp4

Case 2:
https://user-images.githubusercontent.com/56451049/110780509-0dd06100-8265-11eb-991b-2a20bc27baa1.mp4

**Comment by stijndcl** [comment]
> Are you able to reproduce these steps? When I try these steps, the description doesn't open (correctly).
> 
> Case 1:
> https://user-images.githubusercontent.com/56451049/110780776-59830a80-8265-11eb-80b3-c3d016706565.mp4
> 
> Case 2:
> https://user-images.githubusercontent.com/56451049/110780509-0dd06100-8265-11eb-991b-2a20bc27baa1.mp4

A bit peculiar - I can only repoduce this with the live version of the plugin. When playing around in the `development suite`, opening a new exercise always nicely opened in two columns. This might be a bit of a rough one to debug...
Either way all the other problems _are_ reproducable so those _can_ be looked into.
